---
- name: Install packages
  apt:
    name:
      - cron
      - php-gd
      - php-zip
      - php-curl
      - php-mbstring
      - php-ldap
      - python-mysqldb
      - python3-mysqldb
      - php-mysql
      - php-pgsql
      - php-apcu
      - php-xml
      - python-yaml
      - python3-yaml
      - php-redis
      - php-intl
      - php-bcmath
      - php-gmp
      - php-imagick

- name: Check if Nextcloud folder exists
  stat:
    path: "{{ nextcloud_path }}"
  register: result

- import_tasks: install.yml
  when:  not result.stat.exists

- import_tasks: ldap.yml
  when: nextcloud_ldap_enable

- import_tasks: plugins.yml

- import_tasks: configure.yml

- name: Get version number
  shell: 'php occ -V'
  become_user: "{{ nextcloud_system_user }}"
  register: result
  args:
    chdir: "{{ nextcloud_path }}"
  changed_when: false

- name: "Please update Nextcloud from {{ result.stdout.split }} to {{ nextcloud_version }}"
  fail:
    msg: "Please update Nextcloud from {{ result.stdout.split }} to {{ nextcloud_version }}"
  when: nextcloud_version is version(result.stdout.split(' ')[-1], '>')
