---
- name: Enable maintenance mode
  become_user: "{{ nextcloud_system_user }}"
  shell: "php occ maintenance:mode --on"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Stop MySQL, Nginx and Redis
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - nginx
    - redis
    - mysql

- name: "Move Nextcloud dir to {{ nextcloud_path_old }}_{{ nextcloud_version }}"
  command: "mv {{ nextcloud_path }} {{ nextcloud_path_old }}_{{ nextcloud_version }}"

- name: Download and extract new version
  include_tasks: download.yml
  vars:
    nextcloud_download_version: "{{ nextcloud_version }}"
    nextcloud_extract_path: "{{ nextcloud_path }}"

- name: Copy old config file
  copy:
    src: "{{ nextcloud_path_old }}_{{ nextcloud_version }}/config/config.php"
    dest: "{{ nextcloud_path }}/config/config.php"
    remote_src: yes
    owner: "{{ nextcloud_system_user }}"
    group: "{{ nextcloud_system_group }}"

- name: Move apps over to the new install
  command: "mv {{ nextcloud_path_old }}_{{ nextcloud_version }}/apps {{ nextcloud_path }}/apps"

- name: Start MySQL and Redis
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - redis
    - mysql

- name: Run Nextcloud upgrade
  become_user: "{{ nextcloud_system_user }}"
  shell: "php occ upgrade"
  args:
    chdir: "{{ nextcloud_path }}"

- name: Start Nginx
  systemd:
    name: nginx
    state: started

- name: Disable maintenance mode
  become_user: "{{ nextcloud_system_user }}"
  shell: "php occ maintenance:mode --off"
  args:
    chdir: "{{ nextcloud_path }}"
